name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean before build
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf build
      
      - name: Inject VITE_API_SERVER
        run: echo "VITE_API_SERVER=${{ secrets.VITE_API_SERVER }}" > .env

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint || echo "Lint failed"
        continue-on-error: true

      - name: Run unit tests
        run: npm test -- --passWithNoTests

      - name: Build Vite project
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          app_location: "frontend"
          output_location: "dist"
          deployment_action: "upload"